import "./globals.css";
import {manrope} from "@/utils/fonts"


export const metadata = {
  title: "Essential Auction",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope}`}>{children}</body>
    </html>
  );
}
