import "./globals.css";
import {manrope} from "@/package/fonts"
import NavBar from "@/tabs/users/navBar";
import FooterContact from "@/components/users/footerContact";
import SideBar from "@/tabs/admin/sideBar";


 const metadata = {
  title: "Essential Auction",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope}`}>
        <NavBar/>
        <SideBar/>
        {children}
        <FooterContact/>
      </body>
    </html>
  );
}
